[versions]
agp = "7.4.2"
kotlin = "1.8.21"
androidCore = "1.6.0"
coroutines = "1.5.2"
lifecycle = "2.3.0"
browser = "1.5.0"
retrofit = "2.9.0"
loggingInterceptor = "4.9.0"
gson = "2.8.8"
dexter = "6.2.2"
junit = "4.13.2"
testRunner = "1.4.0"
mockito = "2.0.2-beta"
mockwebserver = "2.6.0"
espresso = "3.2.0"

[libraries]
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-all", version.ref = "mockito" }
mockwebserver = { module = "com.squareup.okhttp:mockwebserver", version.ref = "mockwebserver" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }