[versions]
agp = "8.13.1"
kotlin = "2.2.21"
androidCore = "1.17.0"
lifecycle = "2.9.4"
lifecycleProcess = "2.9.4"
browser = "1.9.0"
retrofit = "3.0.0"
loggingInterceptor = "5.3.0"
gson = "2.13.2"
junit = "4.13.2"
espresso = "3.7.0"
koin = "4.1.1"
arrow = "2.2.0"
junitExt = "1.3.0"
startUp = "1.2.0"
activity = "1.11.0"
composeBom = "2025.11.00"
detekt = "1.23.8"
ackpine = "0.16.1"
capturable = "3.0.1"
media3 = "1.8.0"
datastore = "1.1.7"
coroutinesTest = "1.10.2"
mockk = "1.14.6"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startUp" }
androidx-activity-core = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
ackpine-ktx = { module = "ru.solrudev.ackpine:ackpine-ktx", version.ref = "ackpine" }
ackpine-core = { module = "ru.solrudev.ackpine:ackpine-core", version.ref = "ackpine" }
capturable = { module = "dev.shreyaspatil:capturable", version.ref = "capturable" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

#Libs for convention plugin
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-tools-common = { module = "com.android.tools:common", version = "31.13.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
applivery-publish = { id = "com.applivery.android.sdk.publish", version = "unspecified" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }