[versions]
agp = "8.7.3"
kotlin = "2.0.0"
androidCore = "1.10.0"
lifecycle = "2.8.7"
lifecycleProcess = "2.8.7"
browser = "1.8.0"
retrofit = "2.11.0"
loggingInterceptor = "4.12.0"
gson = "2.11.0"
junit = "4.13.2"
espresso = "3.6.1"
koin = "3.5.3"
arrow = "1.2.0"
junitExt = "1.2.1"
startUp = "1.2.0"
activity = "1.9.3"
composeBom = "2025.01.01"
detekt = "1.23.6"
ackpine = "0.10.1"
capturable = "2.1.0"
composeVideo = "1.2.0"
media3 = "1.5.1"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startUp" }
androidx-activity-core = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
ackpine-ktx = { module = "ru.solrudev.ackpine:ackpine-ktx", version.ref = "ackpine" }
capturable = { module = "dev.shreyaspatil:capturable", version.ref = "capturable" }
compose-video = { module = "io.sanghun:compose-video", version.ref = "composeVideo" }

#Libs for convention plugin
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-tools-common = { module = "com.android.tools:common", version = "31.8.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
applivery-publish = { id = "com.applivery.android.sdk.publish", version = "unspecified" }